### ISSUE TITLE
Manage Classes *BUG*

### ISSUE THREAD

**Issue by PezBob** [joeFischetti/478Capstone#8]
When in the manage classes screen, no classes populate in the left window.  When selecting add new class a popup window showing add new student and the class list comes in, but there is no where to put information or add a new class.  Clicking on the Add class button doesn't add anything.

**Comment by joeFischetti** [comment]
Bob,
The class list is empty because your database doesn't actually have any classes.  If you select "Add new class", at the new popup window you need to select the course that that class will belong to.  Then click the "Add Class" button.  A new class pops up in the left side window.  At least it SHOULD, and it does for me.

Classes don't have anything that you can modify.  The class table just has a section number (at UIS we have section letters) and a course number.  (I think we're in CSC478 section B, for example).  

My thought is that the teacher teaches x courses (English 101, and English 202).  They then have y sections of Eng101, and z sections of Eng202.  E101 section 1 may have 5 students, E101 section 2 may have 25 students, etc, but all sections of E101 have the same course info and assignments.  This is why I chose to make the course the main deciding factor, and classes are simply a way to reference the student list.

I won't close this bug until you confirm that your version works this way.  I haven't made any changes to the code.

**Comment by PezBob** [comment]
Looks good now, I was having some weird database interactions but I flushed it all out and pulled fresh copies of everything from GitHub, I think we're in the clear now.  Yeah I'm thinking this was probably due to my dumbassery but I wasn't able to get anything to populate in my first run at it.  Let's go ahead and close this issue down, thanks for checking Joe.
